project_name: apidoc

release:
  github:
    owner: caixw
    name: apidoc
  name_template: '{{.Tag}}'

builds:
  - id: apidoc

    goos:
    - darwin
    - linux
    - windows

    goarch:
    - amd64

    main: ./cmd/apidoc

    binary: apidoc

    flags:
      - -trimpath

    ldflags:
      - -s -w -X github.com/caixw/apidoc/v7/core.commitHash={{.Commit}} -X github.com/caixw/apidoc/v7/core.buildDate={{time "20060102"}}

archives:
  - builds:
    - apidoc
    replacements:
      darwin: macOS
    format_overrides:
    - goos: windows
      format: zip
    files:
    - licence*
    - LICENCE*
    - license*
    - LICENSE*
    - readme*
    - README*
    - changelog*
    - CHANGELOG*

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  skip: true
